db:
  username: root
  password:
  url: jdbc:mysql://localhost:3306/fic
ignored_inventory:
  - '菜单'
  - ''
# BanMode Options: BUNGEE_BAN,BUKKIT_BAN
# BUNGEE_BAN needs the plugin called "BungeeBan", can be downloaded in following url
# https://www.spigotmc.org/resources/bungeeban.8/
ban_mode: "BUKKIT_BAN"
ban_reason: "你被ban了"